Repository insane-devs/spotilink, pull requests merged in 2020-08, with the labels that each got.

#2 refactor(renewToken): use 'expires_in' for accurate token renewals
  src/lib/SpotifyParser.ts
Labels: enhancement

#4 #3 Fix
  src/lib/SpotifyParser.ts
Labels: Type: Fix

#6 Track search priorities
  README.md
  src/lib/SpotifyParser.ts
Labels: Status: Complete, Type: Enhancement
